remote_url = "urcs://urc-uefn.live.ucs.on.epicgames.com"
identity = "0199e79c340c7a9b9a84dd840652bae2"

[store]
max_capacity = 10485760
eviction_delay = 10
max_size = 10737418240
compaction_delay = 30

[file]
direct_write = false
direct_io = false
flush_write = false
